title: BODIPYs
logo: toc.png
description: First electronic excited state properties of 77k BODIPY molecules
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
defaults:
  layout: single
